---
title: "120min_SASP"
author: "Jordan Burton"
date: "5/25/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(RColorBrewer)
library(plotly)
library(limma)
library(qvalue)
library(tidyverse)
library(gridExtra)
library(ggrepel)
library(gplots)
library(knitr)
library(piano)
library(conflicted)
library(mixOmics)
library(clusterProfiler)
library(AnnotationHub)
library(org.Hs.eg.db)
library(VennDiagram)
library(eulerr)
theme_set(theme_bw(base_size = 18))
mycolors <- c("Blue", "Red", "Gray")
names(mycolors) <- c("Blue", "Red", "Gray")
```

```{r conflict, include = FALSE}
conflict_prefer("summarize", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("mutate", "dplyr")
conflict_prefer("arrange", "dplyr")
conflict_prefer("desc", "dplyr")
```

```{r load data}
can_120_lib <- read.csv("data/v16/120min/2022_0513_SSL2_ND_InjvsNon_120min_Spec16_Library_v01_candidates_unpaired_all.csv", stringsAsFactors = F)
pro_120_lib <- read.csv("data/v16/120min/2022_0513_SSL2_ND_InjvsNon_120min_Spec16_Library_v01_Report_Birgit.csv", stringsAsFactors = F)
SASP <- read.csv("SASP_Toolkit/data/Mouse_Core_SASP.csv")
```

```{r prepare candidate files}
candidates <- function(df){
df$minuslogqval <- -1*log10(df$Qvalue)
df$Color <- ifelse(df$AVG.Log2.Ratio >= 0.58 & df$Qvalue < 0.01, "Red", "Grey")
df$Color <- ifelse(df$AVG.Log2.Ratio <= -0.58 & df$Qvalue < 0.01, "Blue", df$Color)
df$Label <- NA
return(df)
}

can_120_lib <- candidates(can_120_lib)
```



```{r candidate venn diagrams}
two_venn_SASP <- function(df1, df2, myfile1, myfile2){
  df1 <- df1 %>% filter(Color != "Grey")
  #df2 <- df2 %>% filter(Color != "Grey")
  #Creating the lists to compare
  R1 <- tolower(df1$Genes)
  R2 <- tolower(df2$Genes)

##----- 2-way Venn diagram

   # Rename the lists according to your data set
overlap <- calculate.overlap(x = list("Protein Candidates" = R1, "SASP Markers" = R2))

   # Generating and exporting the Venn diagram WITH legends
venn.diagram(x = list("Protein Candidates" = R1, "SASP Markers" = R2), #Rename according to the names given in line 57 "overlap"
             filename = myfile1, 
             main = "UniProtID", main.fontface = "bold", main.fontfamily = "sans", #Title on the plot + font
             main.cex = 1.6, main.pos = c(0.5,0.8), #Title size + position
             cex = 1, label.col = "grey9", label.fontfamily = "sans", #Legend size, color and font
             cat.cex = 1.1, cat.col = c("brown", "#4f79a4"), cat.just = list(c(0.07,-4.5), c(0.7,-5)), #Size + color + position on the plot of the circle labels
             cat.default.pos = "outer", cat.fontfamily = "sans", #Position related to the circles + font of the circle labels
             print.mode = "raw", direct.area = TRUE, area.vector = c(length(overlap$a1), length(overlap$a2), length(overlap$a3)), #what to plot
             fill = c("brown", "#4f79a4"), alpha = 0.3, #Filling color of the circles
             col = c("brown", "#4f79a4"), lwd = 2, #Outline color of the circles
             height = 2000, width = 2000, #Size of the plot
             margin = 0.31)

   # Generating and exporting the Venn diagram WITHOUT any legends
venn.diagram(x = list("Protein Candidates" = R1, "SASP Markers" = R2), 
             filename = myfile2,
             cex = 1, label.col = "transparent", label.fontfamily = "sans",
             cat.cex = 1.1, cat.col =  "transparent", cat.just = list(c(0.07,-4.5), c(0.7,-5)),
             cat.default.pos = "outer", cat.fontfamily = "sans",
             print.mode = "raw", direct.area = TRUE, area.vector = c(length(overlap$a1), length(overlap$a2), length(overlap$a3)),
             fill = c("brown", "#4f79a4"), alpha = 0.3,
             col = c("brown", "#4f79a4"), lwd = 2,
             height = 2000, width = 2000,
             margin = 0)
}

two_venn_SASP(df1 = can_120_lib, df2 = SASP, myfile1 = "output/venn/120min/Annotated_Candidate_SASP_Overlap.tiff", myfile2 = "output/venn/120min/Unannotated_Candidate_Candidate_SASP_Overlap.tiff")
```

```{r}
can_120_lib$Genes <- tolower(can_120_lib$Genes)
SASP$Genes <- tolower(SASP$Genes)
SASP_120_lib<- can_120_lib %>% inner_join(SASP, by = "Genes") %>% filter(Color != "Grey")

write.csv(SASP_120_lib, file = "output/venn/120min/22_0525_120min_Candidate_SASP_Overlap.csv")
```

```{r}
All <- can_120_lib %>% filter(grepl('Perox|Mito', ProteinDescriptions) | grepl('Perox|Mito', GO.Cellular.Component) |
                         grepl('Perox|Mito', GO.Molecular.Function) | grepl('Perox|Mito', GO.Biological.Process))
#78 peroxisomal or mitochondrial proteins
Perox <- can_120_lib %>% filter(grepl('Perox', ProteinDescriptions) | grepl('Perox', GO.Cellular.Component) |
                         grepl('Perox', GO.Molecular.Function) | grepl('Perox', GO.Biological.Process))
## 26 peroxisomal proteins, 17 sign altered, 1 up, 16 down
write.csv(Perox, "Peroxisomal_Proteins.csv")

Mito <- can_120_lib %>% filter(grepl('Mito', ProteinDescriptions) | grepl('Mito', GO.Cellular.Component) |
                         grepl('Mito', GO.Molecular.Function) | grepl('Mito', GO.Biological.Process))
##52 mitochondrial proteins, 42 sign altered, 6 up, 36 down
write.csv(Mito, "Mitochondrial_Proteins.csv")
```

```{r}
# data import

df <- read.csv("~/Desktop/ZenoTOF SSL2 Processed data/Spectronaut_Version_Comparison/data/v16/120min/ConsensusPathDB_SASP_Up_results.csv", 
               stringsAsFactors = F)

###############Biological Processes Dotplot with ggplot##############
# filter data for plotting
data <- df %>%
  filter(q.value<0.01) %>%
  filter(term_category=="b") %>% #term category 
  #b = biological process, c = cellular component, m = molecular function
  filter(term_level>=4) %>%
  arrange(desc(GeneRatio))

top10 <- top_n(data, n = 10) # select the top10 pathways to display if applicable


tiff("output/dotplots/SASP_Up_Biological_Processes.tiff", 
     units="in", width=8, height=5, res=300)

S1 <- ggplot(top10, aes(x=GeneRatio , y=factor(pathway, levels=rev(pathway)), 
                        size=count, color=q.value)) + geom_point(alpha = 0.8) + 
  theme_classic()
S1 

S1 = S1+scale_color_gradient(low = "red2",  
                             high = "mediumblue", space = "Lab",
                             limit = c(min(data$q.value), 
                             max(data$q.value)))
S1 + scale_y_discrete(name="") +
  scale_size(range = c(2, 6)) +
  theme(axis.title.x = element_text(size=16),
        axis.text.x  = element_text(size=14, angle = 90,
                                    vjust = 0.5, hjust=1),
        axis.text.y = element_text(size=10))

dev.off()
```

