---
title: "20min_45min_120min"
author: "Jordan Burton"
date: "5/20/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
library(RColorBrewer)
library(plotly)
library(limma)
library(qvalue)
library(tidyverse)
library(gridExtra)
library(ggrepel)
library(gplots)
library(knitr)
library(piano)
library(conflicted)
library(mixOmics)
library(clusterProfiler)
library(AnnotationHub)
library(org.Hs.eg.db)
library(VennDiagram)
library(eulerr)
theme_set(theme_bw(base_size = 18))
mycolors <- c("Blue", "Red", "Gray")
names(mycolors) <- c("Blue", "Red", "Gray")
```

```{r conflict, include = FALSE}
conflict_prefer("summarize", "dplyr")
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
conflict_prefer("mutate", "dplyr")
conflict_prefer("arrange", "dplyr")
```

```{r load data}
can_20_lib <- read.csv("data/v16/20min/22_0520_SSL2_ND_InjvsNon_20minDIA_120minLib_v01_candidates.csv", stringsAsFactors = F)
pro_20_lib <- read.csv("data/v16/20min/22_0520_SSL2_ND_InjvsNon_20minDIA_120minLib_v01_Report_Birgit_Protein_Quant_Pivot.csv", stringsAsFactors = F)

can_45_lib <- read.csv("data/v16/45min/22_0520_SSL2_ND_InjvsNon_45minDIA_120minLib_v01_candidates.csv", stringsAsFactors = F)
pro_45_lib <- read.csv("data/v16/45min/22_0520_SSL2_ND_InjvsNon_45minDIA_120minLib_v01_Report_Birgit_Protein_Quant_Pivot.csv", stringsAsFactors = F)

can_120_lib <- read.csv("data/v16/120min/2022_0513_SSL2_ND_InjvsNon_120min_Spec16_Library_v01_candidates_unpaired_all.csv", stringsAsFactors = F)
pro_120_lib <- read.csv("data/v16/120min/2022_0513_SSL2_ND_InjvsNon_120min_Spec16_Library_v01_Report_Birgit.csv", stringsAsFactors = F)
```

```{r prepare candidate files}
candidates <- function(df){
df$minuslogqval <- -1*log10(df$Qvalue)
df$Color <- ifelse(df$AVG.Log2.Ratio >= 0.58 & df$Qvalue < 0.01, "Red", "Grey")
df$Color <- ifelse(df$AVG.Log2.Ratio <= -0.58 & df$Qvalue < 0.01, "Blue", df$Color)
#df$Label <- NA
return(df)
}

can_20_lib <- candidates(can_20_lib)
can_45_lib <- candidates(can_45_lib)
can_120_lib <- candidates(can_120_lib)
```

```{r candidate venn diagrams}
#myfile1 writes annotated venn
#myfile2 writes unannotated venn
three_venn_can <- function(df1, df2, df3, myfile1, myfile2){
  df1 <- df1 %>% filter(Color != "Grey")
  df2 <- df2 %>% filter(Color != "Grey")
  df3 <- df3 %>% filter(Color != "Grey")
  #Creating the lists to compare
  R1 <- df1$Genes
  R2 <- df2$Genes
  R3 <- df3$Genes

##----- 3-way Venn diagram

   # Rename the lists according to your data set
overlap <- calculate.overlap(x = list("20 min" = R1, "45 min" = R2, "120 min" = R3))

#Calculating the overlaps between the 3 lists

   # Rename according to the names given in line 24 "overlap"
fit <- euler(c("20 min" = length(overlap$a1), "45 min" = length(overlap$a3), "120 min" = length(overlap$a7), 
               "20 min & 45 min" = length(overlap$a2), "20 min & 120 min" = length(overlap$a4), 
               "45 min & 120 ,min" = length(overlap$a6), "20 min & 45 min & 120 min" = length(overlap$a5)), 
             shape = "ellipse") #If some intersections are missing, change "circle" for "ellipse"

   # Generating and exporting the Venn diagram WITH legends
tiff(myfile1, res = 300, height = 6, width = 7, units = "in")
plot (fit,
      labels = list(fontsize = 30, col = c("#4f79a4", "#604878", "#F79646"), lineheight = 5), #Size and color of the circle labels
      fill = c(alpha('#4f79a4',0.5), alpha('#604878',0.5), alpha("#F79646",0.5)),  #Filling color of the circles
      col = c("black", "black", "black"), #Outline color
      quantities = list(fontsize = 25)) #Size of the number labels
dev.off()


      # Generating and exporting the Venn diagram WITHOUT any legends
tiff(myfile2, res = 300, height = 6, width = 7, units = "in")
plot (fit,
      labels = FALSE, #No circle labels
      fill = c(alpha('#4f79a4',0.5), alpha('#604878',0.5), alpha("#F79646",0.5)), 
      col = c("black", "black", "black"),
      quantities = list(fontsize = 25))
dev.off()
}

three_venn_can(df1 = can_20_lib, df2 = can_45_lib, df3 = can_120_lib, myfile1 = "output/venn/gradients/Annotated_Candidate_120min_lib.tiff", myfile2 = "output/venn/gradients/Unannotated_Candidate_120min_lib.tiff")


two_venn_pro <- function(df1, df2, myfile1, myfile2){
  df1 <- df1 %>% filter(Color == "Red")
  df2 <- df2 %>% filter(Color == "Red")
  #Creating the lists to compare
  R1 <- df1$Genes
  R2 <- df2$Genes

##----- 2-way Venn diagram

   # Rename the lists according to your data set
overlap <- calculate.overlap(x = list("20 min" = R1, "120 min" = R2))

   # Generating and exporting the Venn diagram WITH legends
venn.diagram(x = list("20 min" = R1, "120 min" = R2), #Rename according to the names given in line 57 "overlap"
             filename = myfile1, 
             main = "UniProtID", main.fontface = "bold", main.fontfamily = "sans", #Title on the plot + font
             main.cex = 1.6, main.pos = c(0.5,0.8), #Title size + position
             cex = 1, label.col = "grey9", label.fontfamily = "sans", #Legend size, color and font
             cat.cex = 1.1, cat.col = c("brown", "#4f79a4"), cat.just = list(c(0.07,-4.5), c(0.7,-5)), #Size + color + position on the plot of the circle labels
             cat.default.pos = "outer", cat.fontfamily = "sans", #Position related to the circles + font of the circle labels
             print.mode = "raw", direct.area = TRUE, area.vector = c(length(overlap$a1), length(overlap$a2), length(overlap$a3)), #what to plot
             fill = c("#FF7E7A", "#FF2600"), alpha = 0.3, #Filling color of the circles
             col = c("#FF7E7A", "#FF2600"), lwd = 2, #Outline color of the circles
             height = 2000, width = 2000, #Size of the plot
             margin = 0.31)

   # Generating and exporting the Venn diagram WITHOUT any legends
venn.diagram(x = list("20 min" = R1, "120 min" = R2), 
             filename = myfile2,
             cex = 1, label.col = "transparent", label.fontfamily = "sans",
             cat.cex = 1.1, cat.col =  "transparent", cat.just = list(c(0.07,-4.5), c(0.7,-5)),
             cat.default.pos = "outer", cat.fontfamily = "sans",
             print.mode = "raw", direct.area = TRUE, area.vector = c(length(overlap$a1), length(overlap$a2), length(overlap$a3)),
             fill = c("#FF7E7A", "#FF2600"), alpha = 0.3,
             col = c("#FF7E7A", "#FF2600"), lwd = 2,
             height = 2000, width = 2000,
             margin = 0)

}

two_venn_pro(df1 = can_20_lib, df2 = can_120_lib, myfile1 = "output/venn/paper/Up_Candidates_Overlap.tiff", myfile2 = "output/venn/paper/Up_Unannotated_Candidates_Overlap.tiff")
two_venn_pro(df1 = pro_v15_lib, df2 = pro_v16_lib, myfile1 = "output/venn/45min/Annotated_Proteins_Library_v15_vs_v16.tiff", myfile2 = "output/venn/45min/Unannotated_Proteins_Library_v15_vs_v16.tiff")


```

```{r prepare protein quant files}
names_20 <- c("Non_23", "Inj_27", "Non_24", "Inj_29", "Non_26", "Inj_30", "Inj_28", "Non_25")
names_45 <- c("Non_23", "Inj_27", "Non_24", "Inj_28", "Non_25", "Inj_29", "Non_26", "Inj_30")
names_120 <- c("Non_23", "Inj_27", "Non_24", "Inj_28", "Non_25", "Non_26", "Inj_30", "Inj_29")
prepmat <- function(df, names){
  temp <- data.matrix(dplyr::select(df, contains(c("PG.Quantity"))))
  colnames(temp) <- names
  rownames(temp) <- df$PG.Genes
  return(temp)
}


pro_20_lib <- prepmat(pro_20_lib, names_20)
pro_20_lib <- pro_20_lib[,c(1,3,5,8,2,7,4,6)]
pro_45_lib <- prepmat(pro_45_lib, names_45)
pro_45_lib <- pro_45_lib[,c(1,3,5,7,2,4,6,8)]
pro_120_lib <- prepmat(pro_120_lib, names_120)
pro_120_lib <- pro_120_lib[,c(1,3,5,6,2,4,8,7)]
```

```{r volcano plots}
volcano <- function(df, myname){
temp <- ggplot(data = df, aes(x = AVG.Log2.Ratio, y = minuslogqval, col = Color, text = Genes)) + 
  geom_point() +
 # geom_text_repel(aes(x = AVG.Log2.Ratio, y = minuslogqval)) +  
  geom_vline(xintercept = c(-0.58, 0.58), col = "black", linetype = "dashed") +
  geom_hline(yintercept = -log10(0.01), col = "black", linetype = "dashed") +
  scale_color_manual(values = mycolors) +
  ylab("-Log10(q-value)") +
  scale_x_continuous(name = "Log2(fold change):\nInjured vs. Control", limits = c(-7,7), labels = c(-6,-3,0,3,6), breaks = c(-6,-3,0,3,6)) +
  theme_classic() +
  theme(axis.title =element_text(size = 20, color = "black"),
        axis.text = element_text(size = 18, color = "black"),
        legend.position = "none")
ggsave(filename = myname, device = tiff, path = "output/volcano/gradients/", dpi = "print", width = 5, height = 5, units = 'in')  
}

volcano(df = can_20_lib, myname = "can_20_lib")
volcano(df = can_45_lib, myname = "can_45_lib")
volcano(df = can_120_lib, myname = "can_120_lib")
```

```{r pca & heatmaps}
myRamp<-colorRampPalette(colors=c("#0571b0", "#92c5de", "#f7f7f7", "#f4a582", "#ca0020"))

pca_heat <- function(df, pca_name, heat_name){
meds<-apply(df, 2, median, na.rm=TRUE)
nMat<-sweep(df, 2, meds/mean(meds), FUN="/")

pcMat<-nMat
pcMat<-pcMat[complete.cases(pcMat),]
pcMat[pcMat == 0] <-1
pcRes<-prcomp(t(log2(pcMat)), center = TRUE, scale. = TRUE)
pcSum <- summary(pcRes)
PC1label <- paste0("PC1, ",round(100 * pcSum$importance["Proportion of Variance", "PC1"],1), "% of variance")
PC2label <- paste0("PC2, ",round(100 * pcSum$importance["Proportion of Variance", "PC2"],1), "% of variance")

treat <- c(rep("Non-Injured",4), rep("Injured",4)) # needs to be changed as data from replicates is updated

treatment <- factor(treat)
pcPlotFrame<-data.frame(treatment = treatment,
                        sample = colnames(nMat),
                        pcRes$x[,1:5])
pcPlotFrame %>% 
  ggplot(aes(PC1, PC2, label = sample, color = treatment, shape = treatment))+
  geom_point(size=1.8) +
  scale_x_continuous(name=PC1label) +
  scale_y_continuous(name=PC2label) +
  #geom_text_repel(size = 2) +
  scale_color_manual(values = c("red", "#00B050")) +
  theme(legend.position = 'none') +
  #labs(title = "A") #+ 
  stat_ellipse(aes(color = paste0(treatment)))
#ggsave("output/fig2a.emf", width=180, height=480, units="mm")
ggsave(filename = pca_name, device = tiff, path = "output/pca/gradients/")

tiff(file = heat_name)
heatmap.2(t(scale(t(log10(pcMat)))), col = myRamp, trace = 'none', labRow = FALSE)
dev.off()
}

pca_heat(df = pro_20_lib, pca_name = "pro_20_lib", heat_name = "output/heatmap/gradients/pro_20_lib.tiff")
pca_heat(df = pro_45_lib, pca_name = "pro_45_lib", heat_name = "output/heatmap/gradients/pro_45_lib.tiff")
pca_heat(df = pro_120_lib, pca_name = "pro_120_lib", heat_name = "output/heatmap/gradients/pro_120_lib.tiff")
```

```{r rank vs. abundance}
rankvsabun <- function(df, myname, myfile){
df <- data.frame(df)
    df$Abundance <- rowMeans(df)
    df$Genes <- rownames(df)
ggplot(df, aes(x = rank(reorder(Genes, -Abundance)), 
           y = log10(Abundance), 
           text = paste(Genes))) +
  geom_point(alpha = 0.5, position = "jitter", size = 3) +
  xlab("Protein") + ylab("Abundance (log10)") +
  xlim(c(0,4000)) + ylim(c(0,5)) +
  theme(axis.text.x = element_text(angle = 90))+
  ggtitle(myname)

ggsave(filename = myfile, device = tiff, path = "output/rank_vs_abundance/gradients/") 
}

rankvsabun(pro_20_lib, "20 min Gradient", myfile = "pro_20_lib")
rankvsabun(pro_45_lib, "45 min Gradient", myfile = "pro_45_lib")
rankvsabun(pro_120_lib, "120 min Gradient", myfile = "pro_120_lib")
```

```{r kidney injury marker barplots, eval = F}
pro_120_lib <- read.csv("data/v16/120min/2022_0513_SSL2_ND_InjvsNon_120min_Spec16_Library_v01_Report_Birgit.csv", stringsAsFactors = F)
Kim1 <- pro_120_lib[pro_120_lib$"PG.Genes" == "Lcn2",] %>% dplyr::select(contains("PG.Quantity"))
Kim1<- Kim1[,c(1,3,5,6,2,4,8,7)] %>% as.numeric()

marker <- function(df, myfile){
dfmean <- c(mean(df[1:4], na.rm =T), mean(df[5:8], na.rm = T))
dfsd <- c(sd(df[1:4], na.rm = T), sd(df[5:8], na.rm = T))
tiff(myfile, res = 300, height = 4, width = 3, units = "in")
par(lwd = 1.5)
arrows(x0 = barplot(height=dfmean, ylim = c(0,1500), width = 0.5, 
                    names.arg = c("Control", "Injured"),
                    col = "white", border = c("blue", "red"), las =3),
       y0 = dfmean - dfsd,
       y1 = dfmean + dfsd,
       angle = 90, 
       code = 3,
       length = 0.1,
       col = c("blue", "red"))
dev.off()
}
marker(df = Kim1, myfile = "output/Kim1.tiff")

NGal <- pro_120_lib[pro_120_lib$"PG.Genes" == "Havcr1",] %>% dplyr::select(contains("PG.Quantity")) 
NGal <-NGal[,c(1,3,5,6,2,4,8,7)] %>% as.numeric()
marker(df=NGal)
```

